services:
    web:
        build: .
        image: dopplerhq/yodaspeak
        container_name: yodaspeak
        init: true
        environment:
            DOPPLER_TOKEN: $YODASPEAK_SERVICE_TOKEN
        ports:
            - 3000:3000
            - 3443:3443
