name: AWS EC2 destroy with Terraform
on: [workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Destroy
        working-directory: ./aws/ec2
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_AWS_TERRAFORM }}
        run: |
          doppler run --command 'terraform init --upgrade -input=false && \
            echo vpc_id = \"${VPC_ID}\" >> terraform.tfvars && \
            echo subnet_id = \"${SUBNET_ID}\" >> terraform.tfvars && \
            echo region = \"${REGION}\" >> terraform.tfvars && \
            echo key_name = \"${KEY_NAME}\" >> terraform.tfvars && \
            echo cloudflare_zone_id = \"${CLOUDFLARE_ZONE_ID}\" >> terraform.tfvars && \
            echo doppler_service_token = \"${DOPPLER_AWS_APP_SERVICE_TOKEN}\" >> terraform.tfvars && \
            terraform destroy -force -var-file terraform.tfvars -var git_sha=${GITHUB_SHA}'
