name: Heroku Pipeline (Review Apps) Config Vars Sync
on: [workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Install Heroku api plugin
        run: heroku plugins:install api

      - name: Get Pipeline ID
        run: |
          echo "PIPELINE_ID=$(heroku api GET pipelines | jq '.[] | select(.name=="yodaspeak")' | jq -r '.id')" >> $GITHUB_ENV;
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_CI }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Clear current Pipeline Config Vars
        run: |
          printenv;
          eval heroku api PATCH /pipelines/$PIPELINE_ID/stage/review/config-vars --body "'{$(heroku api GET /pipelines/$PIPELINE_ID/stage/review/config-vars | jq -jr ' . | to_entries[] | "\"\(.key)\":null",","' | sed 's/.$//')}'";
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_CI }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Sync Doppler CI secrets to Pipeline Config Vars
        run: eval heroku api PATCH /pipelines/$PIPELINE_ID/stage/review/config-vars --body "'$(doppler secrets download --no-file --format json)'"
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_CI }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
